# Generated by Django 4.0.3 on 2022-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_homethemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_advice',
            name='slug',
            field=models.SlugField(blank=True, max_length=125, null=True),
        ),
    ]
