# Generated by Django 4.0.3 on 2022-03-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_free_advice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_advice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
